### ISSUE TITLE
testes para pre-signed URLs em S3

### ISSUE THREAD

**Issue by fczuardi** [marmotitude/object-storage-tests#31]
Documentacao de como fazer PUT em URL presigned: https://docs.aws.amazon.com/AmazonS3/latest/userguide/example_s3_Scenario_PresignedUrl_section.html

Infelizmente a CLI só faz URL de GET, para PUT tem que ser via AWS SDK libraries.

Python:
- boto3 reference: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/core/boto3.html
  - presigned URLs: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/s3-presigned-urls.html#presigned-urls

**Comment by fczuardi** [comment]
Issue relacionada: https://github.com/aws/aws-cli/issues/3050

**Comment by fczuardi** [comment]
PR relacionado: https://github.com/aws/aws-cli/pull/6993

**Comment by fczuardi** [comment]
o botocore que a aws-cli usa quebra na imagem de docker quando adicionamos o boto3 do apk:

```
aws --version
Traceback (most recent call last):
  File "/usr/bin/aws", line 19, in <module>
    import awscli.clidriver
  File "/usr/lib/python3.11/site-packages/awscli/clidriver.py", line 21, in <module>
    import botocore.session
  File "/usr/lib/python3.11/site-packages/awscli/botocore/session.py", line 27, in <module>
    import botocore.client
  File "/usr/lib/python3.11/site-packages/awscli/botocore/client.py", line 16, in <module>
    from botocore import UNSIGNED, waiter, xform_name
  File "/usr/lib/python3.11/site-packages/awscli/botocore/waiter.py", line 17, in <module>
    from botocore.docs.docstring import WaiterDocstring
  File "/usr/lib/python3.11/site-packages/awscli/botocore/docs/__init__.py", line 15, in <module>
    from botocore.docs.service import ServiceDocumenter
  File "/usr/lib/python3.11/site-packages/awscli/botocore/docs/service.py", line 14, in <module>
    from botocore.docs.client import ClientDocumenter, ClientExceptionsDocumenter
  File "/usr/lib/python3.11/site-packages/awscli/botocore/docs/client.py", line 16, in <module>
    from botocore.docs.example import ResponseExampleDocumenter
  File "/usr/lib/python3.11/site-packages/awscli/botocore/docs/example.py", line 13, in <module>
    from botocore.docs.shape import ShapeDocumenter
  File "/usr/lib/python3.11/site-packages/awscli/botocore/docs/shape.py", line 19, in <module>
    from botocore.utils import is_json_value_header
  File "/usr/lib/python3.11/site-packages/awscli/botocore/utils.py", line 33, in <module>
    import botocore.httpsession
  File "/usr/lib/python3.11/site-packages/awscli/botocore/httpsession.py", line 21, in <module>
    from urllib3.util.ssl_ import (
ImportError: cannot import name 'DEFAULT_CIPHERS' from 'urllib3.util.ssl_' (/home/fcz/.local/lib/python3.11/site-packages/urllib3/util/ssl_.py)
```

é possivel que seja esta issue: https://github.com/boto/botocore/issues/2921
